name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Or windows-latest, macos-latest depending on your needs

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      # Use the latest stable version of setup-python (v5 is current best practice)
      uses: actions/setup-python@v5
      with:
       
        python-version: '3.11' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Ensure pip installs from your requirements.txt
        pip install -r requirements.txt

    - name: Archive app
      run: zip -r release.zip . -x "*.git*" "*.venv/*" # Exclude .venv folder

    - name: Azure Login
      # Ensure AZURE_CREDENTIALS secret is configured in your GitHub repository
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v3
      with:
        app-name: sifra-ai-backend-v2 # Make sure this matches your Azure Web App name
        package: release.zip
